const contentSecurityPolicy = [
  "default-src 'self'",
  "base-uri 'self'",
  "object-src 'none'",
  "frame-ancestors 'self'",
  "form-action 'self'",
  "manifest-src 'self'",
  "worker-src 'self' blob:",
  "font-src 'self' data:",
  "style-src 'self' 'unsafe-inline'",
  [
    "script-src",
    "'self'",
    "'unsafe-inline'",
    "https://analytics.ahrefs.com",
    "https://www.googletagmanager.com",
    "https://www.google-analytics.com",
    "https://www.gstatic.com",
    "https://seowebsites.be",
    "https://*.seowebsites.be",
    "https://*.worf.replit.dev",
  ].join(" "),
  [
    "connect-src",
    "'self'",
    "https://analytics.ahrefs.com",
    "https://www.googletagmanager.com",
    "https://www.google-analytics.com",
    "https://region1.google-analytics.com",
    "https://www.googleapis.com",
    "https://firestore.googleapis.com",
    "https://identitytoolkit.googleapis.com",
    "https://securetoken.googleapis.com",
    "https://firebaseinstallations.googleapis.com",
    "https://firebase.googleapis.com",
    "https://www.gstatic.com",
    "https://api.smugmug.com",
    "https://seowebsites.be",
    "https://*.seowebsites.be",
    "https://*.worf.replit.dev",
  ].join(" "),
  [
    "img-src",
    "'self'",
    "data:",
    "blob:",
    "https://firebasestorage.googleapis.com",
    "https://*.firebasestorage.app",
    "https://images.unsplash.com",
    "https://img.youtube.com",
    "https://i.ytimg.com",
    "https://*.googleusercontent.com",
    "https://cdn.simpleicons.org",
    "https://img.icons8.com",
    "https://analytics.ahrefs.com",
    "https://www.googletagmanager.com",
    "https://www.google-analytics.com",
    "https://seowebsites.be",
    "https://*.seowebsites.be",
    "https://*.worf.replit.dev",
  ].join(" "),
  [
    "media-src",
    "'self'",
    "data:",
    "blob:",
    "https://firebasestorage.googleapis.com",
    "https://*.firebasestorage.app",
  ].join(" "),
  [
    "frame-src",
    "'self'",
    "data:",
    "blob:",
    "https://www.youtube.com",
    "https://www.youtube-nocookie.com",
    "https://my.matterport.com",
    "https://www.google.com",
    "https://maps.google.com",
    "https://seowebsites.be",
    "https://*.seowebsites.be",
    "https://*.worf.replit.dev",
  ].join(" "),
  "upgrade-insecure-requests",
].join("; ");

const permissionsPolicy = [
  "accelerometer=(self)",
  "autoplay=(self)",
  "camera=()",
  "clipboard-read=()",
  "clipboard-write=(self)",
  "fullscreen=(self)",
  "geolocation=()",
  "gyroscope=(self)",
  "magnetometer=()",
  "microphone=()",
  "payment=()",
  "usb=()",
  "browsing-topics=()",
  "interest-cohort=()",
].join(", ");

const securityHeaders = [
  {
    key: "Strict-Transport-Security",
    value: "max-age=31536000; includeSubDomains; preload",
  },
  {
    key: "Content-Security-Policy",
    value: contentSecurityPolicy,
  },
  {
    key: "X-Frame-Options",
    value: "SAMEORIGIN",
  },
  {
    key: "X-Content-Type-Options",
    value: "nosniff",
  },
  {
    key: "Referrer-Policy",
    value: "strict-origin-when-cross-origin",
  },
  {
    key: "Permissions-Policy",
    value: permissionsPolicy,
  },
];

module.exports = {
  contentSecurityPolicy,
  permissionsPolicy,
  securityHeaders,
};
