export const reportCopy = {
  score: "Totaalscore",
  summary: "Samenvatting",
  passed: "Geslaagd",
  warnings: "Aandacht",
  errors: "Problemen",
  quickWins: "Quick Wins Scorecard",
  totalWords: "Totaal woorden",
  stopWords: "Stopwoorden",
  topKeyword: "Topkeyword",
  totalChecks: "Controles",
  aioGeo: "AIO/GEO Health Check",
  keywordDensity: "Keyword density",
  singleWords: "Eén woord",
  doubleWords: "Twee woorden",
  tripleWords: "Drie woorden",
  phrase: "Keyword",
  count: "Aantal",
  locations: "Locaties",
  density: "Density",
  details: "Gedetailleerd rapport",
  strengths: "Sterke punten",
  issues: "Belangrijkste verbeterpunten",
  pageDetails: "Pagina- en technische gegevens",
  noDensity: "Voor deze analyse zijn geen keywordgegevens beschikbaar.",
  advice: "Aanbevolen actie",
} as const;
