import type { SeoGeoChecklistCategory, ToolCard } from "./tools";
import { seoGeoChecklistCategories } from "./tools";

export const englishToolCards: ToolCard[] = [
  { id: "website-analyse", name: "Website analysis", href: "/website-analyse", icon: "seo", tag: "Free scan", desc: "Check your website's SEO, performance, technical setup, content and AI search visibility.", cta: "Start the free analysis", previewTitle: "A clear score out of 100", previewText: "See a clear score, findings by category and practical advice you can open straight away.", previewPoints: ["SEO and technical setup", "Core Web Vitals", "AI search visibility"] },
  { id: "seo-geo-checklist", name: "SEO/GEO checklist", href: "/tools/seo-geo-checklist", icon: "checklist", tag: "Interactive + PDF", desc: "Review your page step by step and download your selected actions as a VisualVibe PDF.", cta: "Build your checklist", previewTitle: "A checklist for Google and AI search", previewText: "Tick off completed work, track your progress and take a branded PDF back to your team.", previewPoints: ["Technical SEO", "AEO/GEO", "Structured data"] },
];

const categoryText: Record<string, [string, string]> = {
  "technical-seo": ["Technical SEO", "Make sure search engines can find, understand and index your page correctly."],
  "content-keywords": ["Content & keywords", "Clarify who the page is for, which problem it solves and how people search for it."],
  "aio-geo": ["AEO/GEO & AI search visibility", "Write for conventional results as well as answers and summaries generated by AI systems."],
  "structured-data": ["Structured data", "Provide explicit context so search engines do not have to infer important details."],
  "performance-media": ["Performance & images", "Keep the page fast, clear and usable on desktop and mobile."],
  "local-seo": ["Local search visibility", "Make it clear where you work and why local customers can trust you."],
};

const itemText: Record<string, [string, string]> = {
  "technical-seo-indexable": ["The page is indexable and is not set to noindex", "Check robots rules, meta robots, the canonical and any protected environments."],
  "technical-seo-canonical": ["The canonical points to the correct public URL", "Avoid ambiguity between trailing-slash, parameter and language variants."],
  "technical-seo-title-description": ["The title and meta description are unique and compelling", "Focus on one clear search intent and write the description as a useful invitation."],
  "technical-seo-headings": ["The page has one clear H1 and a logical H2/H3 structure", "Headings should make the content easy to scan for readers, search engines and AI systems."],
  "content-primary-keyword": ["The main keyword appears naturally in the title, introduction and a subheading", "Do not force it. One clear focus is better than many awkward variants."],
  "content-search-intent": ["The page answers the reader's actual search intent", "Explain what it is, who it is for, what it offers and what to do next."],
  "content-proof": ["The page includes evidence", "Use case studies, results, examples, screenshots, reviews or a concrete process."],
  "content-internal-links": ["Relevant services, case studies and knowledge-base articles are linked", "Help readers and crawlers continue through the site logically."],
  "aio-geo-direct-answer": ["A concise direct answer appears near the top", "Clear definitions, steps and summaries are easier for AI systems to cite."],
  "aio-geo-faq": ["Frequently asked questions answer genuine customer questions", "Use questions a prospect would actually ask, not promotional headings."],
  "aio-geo-entities": ["Important entities are named explicitly", "Include the brand, region, service, audience, technologies and concrete applications."],
  "aio-geo-process": ["The process or sequence of steps is clearly explained", "A clear process helps readers and AI systems understand what will happen."],
  "structured-data-organization": ["Organization or LocalBusiness schema is present where relevant", "Include the business name, URL, logo, contact details and service area where appropriate."],
  "structured-data-breadcrumb": ["BreadcrumbList schema follows the visible page structure", "Breadcrumbs help users and search engines understand the page's position."],
  "structured-data-faq": ["FAQ schema is used only for visible questions and answers", "Do not add hidden or invented FAQs. Structured data must match visible content."],
  "structured-data-service": ["Service pages use appropriate Service data", "Describe the service, provider, region and relevant categories where useful."],
  "performance-lcp-image": ["The main hero image is optimised for LCP", "Use suitable dimensions and modern compression, and avoid an unnecessarily heavy first image."],
  "performance-alt-text": ["Meaningful images have relevant alternative text", "Describe the image's contribution. Decorative images can use empty alt text."],
  "performance-cache": ["Static assets use an efficient cache policy", "Logos, fonts and versioned scripts should not be cached for an unnecessarily short period."],
  "performance-render-blocking": ["CSS, fonts and scripts minimise render blocking", "Measure the first HTML response, LCP and blocking time, not only total file size."],
  "local-seo-business-info": ["The business name, region, contact details and services are clear", "Local signals help users and search engines understand where the business operates."],
  "local-seo-regions": ["Important regions have useful, dedicated pages", "Avoid empty place-name pages. Add genuine context, case studies and services for each region."],
  "local-seo-reviews": ["Reviews, case studies or local references support credibility", "Evidence from the region is usually stronger than a generic claim."],
  "local-seo-nap": ["The name, address and contact details are consistent", "Keep the website, Google Business Profile and social profiles aligned."],
};

export const englishSeoGeoChecklistCategories: SeoGeoChecklistCategory[] = seoGeoChecklistCategories.map((category) => ({
  ...category,
  title: categoryText[category.id][0],
  intro: categoryText[category.id][1],
  items: category.items.map((item) => ({ ...item, title: itemText[item.id][0], help: itemText[item.id][1] })),
}));
